name: tswin
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flame: ^1.7.3
  flame_forge2d: ^0.13.0+1
  another_flushbar: ^1.12.30
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  shared_preferences:
  provider: ^6.1.2
  fluttertoast: ^8.2.8
  dio: ^5.6.0
  flutter_widget_from_html:
  flutter_share: ^2.0.0
  url_launcher:
  webview_flutter:
  image_picker: ^1.1.2
  just_audio: ^0.9.40
  animated_text_kit: ^4.2.2
  connectivity_plus: ^5.0.2
  url_strategy: ^0.3.0
  share_plus: ^10.0.2
  http:
  socket_io_client: ^2.0.3+1
  draggable_fab: ^0.1.4
  add_to_cart_animation: ^2.0.4
  fwfh_text_style: ^2.23.8
  file_picker: ^8.1.2


  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assetss/images/
    - assetss/images/coin/
    - assetss/images/robot/
    - assetss/images/explosion/
    - assetss/
    - assets/
    - assets/icons/
    - assets/music/
    - assets/images/
    - assets/person/
    - assets/category/
    - assets/aviator/
    - assets/dragontiger/
    - assets/chips/
    - assets/cards/
    - assets/music/dragontiger.mp3


